In [1]:
import numpy as np
import pandas as pd
import matplotlib as mlt
import seaborn as sns
import os

In [2]:
allrounders_df=pd.read_csv('All_rounders.csv')
allrounders_df

,allround//0,allround/Player,allround/Country,allround/Mat,allround/Inns,allround/Runs,allround/Avg,allround/Overs,allround/Wkts,allround/Avg_Bowl,allround/Ca,allround/Rating
0,,Player,Country,Mat,Batting,Bowling,Ca,Rating*,NaN,NaN,NaN,NaN
1,Inns,Runs,Avg,Overs,Wkts,Avg,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Mohammad Hafeez*,Pakistan,119,108,2514,26.46,207.1,61.0,22.38,30.0,4.09
3,2,Shoaib Malik*,ICC World XI,124,111,2435,31.22,95,28.0,24.11,50.0,7.11
4,3,Shakib Al Hasan*,Bangladesh,109,107,2243,23.12,397.3,128.0,21.22,25.0,1.90
5,4,G J Maxwell*,Australia,98,90,2159,28.41,144.1,39.0,27.59,41.0,0.82
6,5,Mahmudullah*,Bangladesh,121,113,2122,23.58,140.5,38.0,26.63,46.0,-3.05
7,6,K J O'Brien*,Ireland,110,103,1973,21.22,152.5,58.0,19.81,40.0,1.40
8,7,Mohammad Nabi*,Afghanistan,104,96,1686,21.08,324.4,84.0,28.27,54.0,-7.20
9,8,K A Pollard*,West Indies,101,83,1569,25.31,142.4,42.0,28.29,43.0,-2.98
10,9,Shahid Afridi,ICC World XI,99,91,1416,17.92,361.2,98.0,24.45,30.0,-6.52
11,10,H H Pandya*,India,87,67,1271,25.42,223.5,69.0,26.43,44.0,-1.01
12,11,Sikandar Raza*,Zimbabwe,66,63,1259,20.98,141,38.0,26.66,28.0,-5.67
13,12,D J Bravo*,West Indies,91,74,1255,22.02,250.5,78.0,26.10,44.0,-4.09
14,13,N L T C Perera*,ICC World XI,84,74,1204,23.15,183.4,51.0,33.67,30.0,-10.51
15,14,C O Obuya*,Kenya,52,48,1111,29.24,65.2,25.0,18.08,28.0,11.16
16,15,R P Burl*,Zimbabwe,58,53,882,25.94,114,39.0,21.36,29.0,4.58
17,16,G H Dockrell*,Ireland,115,70,842,20.05,256.2,81.0,22.63,55.0,-2.58
18,17,P M Seelaar*,Netherlands,77,46,591,17.38,188.4,58.0,22.24,32.0,-4.86
19,18,D J G Sammy,West Indies,68,52,587,17.26,152.4,44.0,25.36,31.0,-8.10
20,19,M J Santner*,New Zealand,83,56,530,17.10,286.2,91.0,22.21,31.0,-5.11
21,* All Rounder Rating = Batting Average - Bowli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
missing_value=['N/a','na','NaN']
allrounders_df=pd.read_csv('All_rounders.csv',na_values=missing_value)
allrounders_df.isnull().sum()

allround//0          0
allround/Player      1
allround/Country     1
allround/Mat         1
allround/Inns        1
allround/Runs        1
allround/Avg         2
allround/Overs       2
allround/Wkts        3
allround/Avg_Bowl    3
allround/Ca          3
allround/Rating      3
dtype: int64

In [4]:
allrounders_df.rename(columns={'allround//0':'id','allround/Player':'Player','allround/Country':'country','allround/Inns':'Innings',
                              'allround/Runs':'Runs','allround/Avg':'Batting_avg','allround/Wkts':'wickets','allround/Avg_Bowl':'Bowling_avg',
                              'allround/Ca':'Catches','allround/Mat':'mat','allround/Overs':'overs','allround/Rating':'rating'},inplace=True)

In [5]:
allrounders_df

,id,Player,country,mat,Innings,Runs,Batting_avg,overs,wickets,Bowling_avg,Catches,rating
0,,Player,Country,Mat,Batting,Bowling,Ca,Rating*,NaN,NaN,NaN,NaN
1,Inns,Runs,Avg,Overs,Wkts,Avg,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Mohammad Hafeez*,Pakistan,119,108,2514,26.46,207.1,61.0,22.38,30.0,4.09
3,2,Shoaib Malik*,ICC World XI,124,111,2435,31.22,95,28.0,24.11,50.0,7.11
4,3,Shakib Al Hasan*,Bangladesh,109,107,2243,23.12,397.3,128.0,21.22,25.0,1.90
5,4,G J Maxwell*,Australia,98,90,2159,28.41,144.1,39.0,27.59,41.0,0.82
6,5,Mahmudullah*,Bangladesh,121,113,2122,23.58,140.5,38.0,26.63,46.0,-3.05
7,6,K J O'Brien*,Ireland,110,103,1973,21.22,152.5,58.0,19.81,40.0,1.40
8,7,Mohammad Nabi*,Afghanistan,104,96,1686,21.08,324.4,84.0,28.27,54.0,-7.20
9,8,K A Pollard*,West Indies,101,83,1569,25.31,142.4,42.0,28.29,43.0,-2.98
10,9,Shahid Afridi,ICC World XI,99,91,1416,17.92,361.2,98.0,24.45,30.0,-6.52
11,10,H H Pandya*,India,87,67,1271,25.42,223.5,69.0,26.43,44.0,-1.01
12,11,Sikandar Raza*,Zimbabwe,66,63,1259,20.98,141,38.0,26.66,28.0,-5.67
13,12,D J Bravo*,West Indies,91,74,1255,22.02,250.5,78.0,26.10,44.0,-4.09
14,13,N L T C Perera*,ICC World XI,84,74,1204,23.15,183.4,51.0,33.67,30.0,-10.51
15,14,C O Obuya*,Kenya,52,48,1111,29.24,65.2,25.0,18.08,28.0,11.16
16,15,R P Burl*,Zimbabwe,58,53,882,25.94,114,39.0,21.36,29.0,4.58
17,16,G H Dockrell*,Ireland,115,70,842,20.05,256.2,81.0,22.63,55.0,-2.58
18,17,P M Seelaar*,Netherlands,77,46,591,17.38,188.4,58.0,22.24,32.0,-4.86
19,18,D J G Sammy,West Indies,68,52,587,17.26,152.4,44.0,25.36,31.0,-8.10
20,19,M J Santner*,New Zealand,83,56,530,17.10,286.2,91.0,22.21,31.0,-5.11
21,* All Rounder Rating = Batting Average - Bowli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
allrounders_df.drop(['mat','overs','rating'], axis=1 , inplace=True )
allrounders_df

,id,Player,country,Innings,Runs,Batting_avg,wickets,Bowling_avg,Catches
0,,Player,Country,Batting,Bowling,Ca,NaN,NaN,NaN
1,Inns,Runs,Avg,Wkts,Avg,NaN,NaN,NaN,NaN
2,1,Mohammad Hafeez*,Pakistan,108,2514,26.46,61.0,22.38,30.0
3,2,Shoaib Malik*,ICC World XI,111,2435,31.22,28.0,24.11,50.0
4,3,Shakib Al Hasan*,Bangladesh,107,2243,23.12,128.0,21.22,25.0
5,4,G J Maxwell*,Australia,90,2159,28.41,39.0,27.59,41.0
6,5,Mahmudullah*,Bangladesh,113,2122,23.58,38.0,26.63,46.0
7,6,K J O'Brien*,Ireland,103,1973,21.22,58.0,19.81,40.0
8,7,Mohammad Nabi*,Afghanistan,96,1686,21.08,84.0,28.27,54.0
9,8,K A Pollard*,West Indies,83,1569,25.31,42.0,28.29,43.0
10,9,Shahid Afridi,ICC World XI,91,1416,17.92,98.0,24.45,30.0
11,10,H H Pandya*,India,67,1271,25.42,69.0,26.43,44.0
12,11,Sikandar Raza*,Zimbabwe,63,1259,20.98,38.0,26.66,28.0
13,12,D J Bravo*,West Indies,74,1255,22.02,78.0,26.10,44.0
14,13,N L T C Perera*,ICC World XI,74,1204,23.15,51.0,33.67,30.0
15,14,C O Obuya*,Kenya,48,1111,29.24,25.0,18.08,28.0
16,15,R P Burl*,Zimbabwe,53,882,25.94,39.0,21.36,29.0
17,16,G H Dockrell*,Ireland,70,842,20.05,81.0,22.63,55.0
18,17,P M Seelaar*,Netherlands,46,591,17.38,58.0,22.24,32.0
19,18,D J G Sammy,West Indies,52,587,17.26,44.0,25.36,31.0
20,19,M J Santner*,New Zealand,56,530,17.10,91.0,22.21,31.0
21,* All Rounder Rating = Batting Average - Bowli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
allrounders_df.dropna(inplace=True)

In [8]:
allrounders_df = allrounders_df.astype({"wickets":'int', "Catches":'int'})

In [9]:
allrounders_df

,id,Player,country,Innings,Runs,Batting_avg,wickets,Bowling_avg,Catches
2,1,Mohammad Hafeez*,Pakistan,108,2514,26.46,61,22.38,30
3,2,Shoaib Malik*,ICC World XI,111,2435,31.22,28,24.11,50
4,3,Shakib Al Hasan*,Bangladesh,107,2243,23.12,128,21.22,25
5,4,G J Maxwell*,Australia,90,2159,28.41,39,27.59,41
6,5,Mahmudullah*,Bangladesh,113,2122,23.58,38,26.63,46
7,6,K J O'Brien*,Ireland,103,1973,21.22,58,19.81,40
8,7,Mohammad Nabi*,Afghanistan,96,1686,21.08,84,28.27,54
9,8,K A Pollard*,West Indies,83,1569,25.31,42,28.29,43
10,9,Shahid Afridi,ICC World XI,91,1416,17.92,98,24.45,30
11,10,H H Pandya*,India,67,1271,25.42,69,26.43,44
12,11,Sikandar Raza*,Zimbabwe,63,1259,20.98,38,26.66,28
13,12,D J Bravo*,West Indies,74,1255,22.02,78,26.10,44
14,13,N L T C Perera*,ICC World XI,74,1204,23.15,51,33.67,30
15,14,C O Obuya*,Kenya,48,1111,29.24,25,18.08,28
16,15,R P Burl*,Zimbabwe,53,882,25.94,39,21.36,29
17,16,G H Dockrell*,Ireland,70,842,20.05,81,22.63,55
18,17,P M Seelaar*,Netherlands,46,591,17.38,58,22.24,32
19,18,D J G Sammy,West Indies,52,587,17.26,44,25.36,31
20,19,M J Santner*,New Zealand,56,530,17.10,91,22.21,31

In [10]:
allrounders_df.to_csv('updated_allrounder.csv',index=False)